name: cicd-actions
on:
  pull_request:
    types:
      - closed
    branches:
      - "master"
    paths:
      - "**.js"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies & Run Tests
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm test
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
x 